package: once
version: '1.0.0'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/once


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.8



page:
    title: translate:once_title
    prio: 100
    icon: rex-icon fa-gear
    perm: admin
